### ISSUE TITLE
Getting an error while build this code

### ISSUE THREAD

**Issue by thummim** [nfvri/ovs-dpdk-telemetry-exporter#2]
I want to edit some code of this code.
but while I am trying to build I get this error, what should I check?
```
root@pcvm:~/ovs-dpdk-telemetry-exporter# make build
docker build -t nfvri/ovs-dpdk-telemetry-exporter:0.1 .
Sending build context to Docker daemon  2.188MB
Step 1/9 : FROM debian:stable
 ---> 7404e946945f
Step 2/9 : LABEL Author="Victor Timofei <victor@vtimothy.com>"
 ---> Using cache
 ---> b52e50cee89a
Step 3/9 : LABEL Vendor="Intracom Telecom S.A."
 ---> Using cache
 ---> f653ff5034fe
Step 4/9 : LABEL Description="OVS-DPDK Telemetry exporter image"
 ---> Using cache
 ---> d257902d226d
Step 5/9 : RUN apt-get update && apt-get install -y python3 python3-pip && apt-get clean
 ---> Running in c226623535e5
Get:1 http://deb.debian.org/debian stable InRelease [151 kB]
Get:2 http://deb.debian.org/debian stable-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security stable-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian stable/main amd64 Packages [8787 kB]
Get:5 http://deb.debian.org/debian stable-updates/main amd64 Packages [12.7 kB]
Get:6 http://deb.debian.org/debian-security stable-security/main amd64 Packages [134 kB]
Fetched 9185 kB in 3s (3431 kB/s)
Reading package lists...
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update && apt-get install -y python3 python3-pip && apt-get clean' returned a non-zero code: 100
make: *** [Makefile:15: build-ovs-dpdk-telemetry-exporter] Error 100
```

**Comment by angelouev** [comment]
Hello @thummim ,

Your problem seems to come from the build environment, namely you don't seem to have access to run apt-get update. If you are indeed behind a proxy, try the Dockerfile-proxy from the issue branch:
1. Checkout the branch with: `git checkout  2-getting-an-error-while-build-this-code` 
2. Use the Dockerfile-proxy to build with the extra build arguments to specify your proxy, e.g.:
`$ docker build -f Dockerfile-proxy --build-arg="BUILD_PROXY=http://<proxy>:<port>" --build-arg="BUILD_NO_PROXY=127.0.0.1,localhost" -t nfvri/ovs-dpdk-telemetry-exporter:0.1 .`

Hope this helps, please report back if it worked for you.

Thanks,
Vangelis

**Comment by thummim** [comment]
Thank you so much for the fast reply and help.
What IP should I use for the proxy and port?

**Comment by thummim** [comment]
actually, since you had change the base image (debian:stable -> debian:bullseye), it worked with general build without using docker-proxy.
thank you so much!
